MODEL:
  TYPE: swin
  NAME: debug
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
DATA:
  NUM_WORKERS: 10
  BATCH_SIZE: 64
  DATA_PATH: /home/datasets/imagenet
  DATASET: imagenet
MS_POLICY: ms_policy/policy_tiny-8bit.txt