MODEL:
  TYPE: swin
  NAME: swin_small_patch4_window7_224
  DROP_PATH_RATE: 0.3
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
DATA:
  NUM_WORKERS: 10
  BATCH_SIZE: 128
  DATA_PATH: /projects/dl65/m3_imagenet
  DATASET: imagenet
MS_POLICY: ms_policy/policy_tiny-8bit.txt